version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - ./.env.dev

  web-backend:
    build: backend/
    command: sh -cx "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  web-frontend:
    build: frontend/
    ports:
      - 3000:3000